name: generate_page
description: "Run perf-test and generate github pages"

inputs:
  TEST: 
    required: true
    description: "Test to run"
  GITHUB_TOKEN: 
    required: true
    description: "Token for github checkin"
  AZURE_STORAGE_ACCOUNT:
    required: true
    description: "Storage account name"
  AZURE_STORAGE_ACCOUNT_CONTAINER:
    required: true
    description: "Storage container name"
  AZURE_STORAGE_ACCESS_KEY: 
    required: true
    description: "Access key for the storage account"

runs:
  using: "composite"
  steps:
    # Pre-run cleanup
    - name: "Cleanup before test"
      shell: bash
      run: |
        rm -rf /mnt/blob_mnt
        rm -rf /mnt/tempcache/*

    # Run the benchmark script 
    - name: "Run Benchmark Script : ${{ inputs.TEST }}"
      shell: bash
      run: |
        ./perf_testing/scripts/fio_bench.sh /mnt/blob_mnt ${{ inputs.TEST }}
      env:
        AZURE_STORAGE_ACCOUNT:  ${{ inputs.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_ACCOUNT_CONTAINER: ${{ inputs.AZURE_STORAGE_ACCOUNT_CONTAINER }}
        AZURE_STORAGE_ACCESS_KEY: ${{ inputs.AZURE_STORAGE_ACCESS_KEY }}
    
    # Print blobfuse2 logs
    - name: "Print logs : ${{ inputs.TEST }}"
      shell: bash
      run: cat ./blobfuse2.log
      if: always()

    # Print the results generated
    - name: "Print latest results : ${{ inputs.TEST }}"
      shell: bash
      run: cat ./${{ inputs.TEST }}_bandwidth/results.json
      if: always()

    # Push the results and publish the graphs
    - name: "Update Benchmark Results : ${{ inputs.TEST }}"
      uses: benchmark-action/github-action-benchmark@v1
      with:
        output-file-path: ${{ inputs.TEST }}_bandwidth/results.json
        tool: 'customBiggerIsBetter'
        alert-threshold: "160%"
        max-items-in-chart: 100
        github-token: ${{ inputs.GITHUB_TOKEN }}
        fail-on-alert: true
        auto-push: true
        comment-on-alert: true
        gh-pages-branch: benchmarks
        benchmark-data-dir-path: bandwidth/${{ inputs.TEST }}