/*
    _____           _____   _____   ____          ______  _____  ------
   |     |  |      |     | |     | |     |     | |       |            |
   |     |  |      |     | |     | |     |     | |       |            |
   | --- |  |      |     | |-----| |---- |     | |-----| |-----  ------
   |     |  |      |     | |     | |     |     |       | |       |
   | ____|  |_____ | ____| | ____| |     |_____|  _____| |_____  |_____


   Licensed under the MIT License <http://opensource.org/licenses/MIT>.

   Copyright © 2020-2025 Microsoft Corporation. All rights reserved.
   Author : <blobfusedev@microsoft.com>

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: service.proto

package service

import (
	models "github.com/Azure/azure-storage-fuse/v2/internal/dcache/rpc/gen-go-grpc/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x0edcache.service\x1a\fmodels.proto2\xc3\x05\n" +
	"\fChunkService\x12B\n" +
	"\x05Hello\x12\x1b.dcache.models.HelloRequest\x1a\x1c.dcache.models.HelloResponse\x12K\n" +
	"\bGetChunk\x12\x1e.dcache.models.GetChunkRequest\x1a\x1f.dcache.models.GetChunkResponse\x12K\n" +
	"\bPutChunk\x12\x1e.dcache.models.PutChunkRequest\x1a\x1f.dcache.models.PutChunkResponse\x12Q\n" +
	"\n" +
	"PutChunkDC\x12 .dcache.models.PutChunkDCRequest\x1a!.dcache.models.PutChunkDCResponse\x12T\n" +
	"\vRemoveChunk\x12!.dcache.models.RemoveChunkRequest\x1a\".dcache.models.RemoveChunkResponse\x12E\n" +
	"\x06JoinMV\x12\x1c.dcache.models.JoinMVRequest\x1a\x1d.dcache.models.JoinMVResponse\x12K\n" +
	"\bUpdateMV\x12\x1e.dcache.models.UpdateMVRequest\x1a\x1f.dcache.models.UpdateMVResponse\x12H\n" +
	"\aLeaveMV\x12\x1d.dcache.models.LeaveMVRequest\x1a\x1e.dcache.models.LeaveMVResponse\x12N\n" +
	"\tGetMVSize\x12\x1f.dcache.models.GetMVSizeRequest\x1a .dcache.models.GetMVSizeResponseBPZNgithub.com/Azure/azure-storage-fuse/v2/internal/dcache/rpc/gen-go-grpc/serviceb\x06proto3"

var file_service_proto_goTypes = []any{
	(*models.HelloRequest)(nil),        // 0: dcache.models.HelloRequest
	(*models.GetChunkRequest)(nil),     // 1: dcache.models.GetChunkRequest
	(*models.PutChunkRequest)(nil),     // 2: dcache.models.PutChunkRequest
	(*models.PutChunkDCRequest)(nil),   // 3: dcache.models.PutChunkDCRequest
	(*models.RemoveChunkRequest)(nil),  // 4: dcache.models.RemoveChunkRequest
	(*models.JoinMVRequest)(nil),       // 5: dcache.models.JoinMVRequest
	(*models.UpdateMVRequest)(nil),     // 6: dcache.models.UpdateMVRequest
	(*models.LeaveMVRequest)(nil),      // 7: dcache.models.LeaveMVRequest
	(*models.GetMVSizeRequest)(nil),    // 8: dcache.models.GetMVSizeRequest
	(*models.HelloResponse)(nil),       // 9: dcache.models.HelloResponse
	(*models.GetChunkResponse)(nil),    // 10: dcache.models.GetChunkResponse
	(*models.PutChunkResponse)(nil),    // 11: dcache.models.PutChunkResponse
	(*models.PutChunkDCResponse)(nil),  // 12: dcache.models.PutChunkDCResponse
	(*models.RemoveChunkResponse)(nil), // 13: dcache.models.RemoveChunkResponse
	(*models.JoinMVResponse)(nil),      // 14: dcache.models.JoinMVResponse
	(*models.UpdateMVResponse)(nil),    // 15: dcache.models.UpdateMVResponse
	(*models.LeaveMVResponse)(nil),     // 16: dcache.models.LeaveMVResponse
	(*models.GetMVSizeResponse)(nil),   // 17: dcache.models.GetMVSizeResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: dcache.service.ChunkService.Hello:input_type -> dcache.models.HelloRequest
	1,  // 1: dcache.service.ChunkService.GetChunk:input_type -> dcache.models.GetChunkRequest
	2,  // 2: dcache.service.ChunkService.PutChunk:input_type -> dcache.models.PutChunkRequest
	3,  // 3: dcache.service.ChunkService.PutChunkDC:input_type -> dcache.models.PutChunkDCRequest
	4,  // 4: dcache.service.ChunkService.RemoveChunk:input_type -> dcache.models.RemoveChunkRequest
	5,  // 5: dcache.service.ChunkService.JoinMV:input_type -> dcache.models.JoinMVRequest
	6,  // 6: dcache.service.ChunkService.UpdateMV:input_type -> dcache.models.UpdateMVRequest
	7,  // 7: dcache.service.ChunkService.LeaveMV:input_type -> dcache.models.LeaveMVRequest
	8,  // 8: dcache.service.ChunkService.GetMVSize:input_type -> dcache.models.GetMVSizeRequest
	9,  // 9: dcache.service.ChunkService.Hello:output_type -> dcache.models.HelloResponse
	10, // 10: dcache.service.ChunkService.GetChunk:output_type -> dcache.models.GetChunkResponse
	11, // 11: dcache.service.ChunkService.PutChunk:output_type -> dcache.models.PutChunkResponse
	12, // 12: dcache.service.ChunkService.PutChunkDC:output_type -> dcache.models.PutChunkDCResponse
	13, // 13: dcache.service.ChunkService.RemoveChunk:output_type -> dcache.models.RemoveChunkResponse
	14, // 14: dcache.service.ChunkService.JoinMV:output_type -> dcache.models.JoinMVResponse
	15, // 15: dcache.service.ChunkService.UpdateMV:output_type -> dcache.models.UpdateMVResponse
	16, // 16: dcache.service.ChunkService.LeaveMV:output_type -> dcache.models.LeaveMVResponse
	17, // 17: dcache.service.ChunkService.GetMVSize:output_type -> dcache.models.GetMVSizeResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
