#
# Share details
#
#account: 0lrxscnams20py01ex
account: sjc22prdste06hnfsv3acc1
container: nfsv3test
#container: mycont
cloud_suffix: blob.preprod.core.windows.net
port: 2048

#
# NFS mount options
# These have the same name and meaning as Linux NFS client mount options.
# Also note that only a subset of Linux mount options are supported.
# readdir_maxcount
# lookupcache: all|none|pos|positive
#
nconnect: 1
timeo: 600
retrans: 2
acregmin: 3
acregmax: 60
acdirmin: 30
acdirmax: 60
actimeo: 300
lookupcache: all
rsize: 1048576
wsize: 1048576

#
# Misc options
#
readdir_maxcount: 1048576
fuse_max_background: 4096

#
# Cache config
#
# We cache the following:
# - file/dir attributes
# - lookup results
# - readdir data
# - file data
#
# attributes are cached in the kernel and can be controlled by the following
# mount options:
# - acregmin/acregmax
# - acdirmin/acdirmax
# - actimeo
# - lookupcache
#
# Attribute caching can be disabled by setting actimeo to 0.
#
# Readdir data can be cached in the kernel and/or user caches.
# It can be controlled using cache.readdir.* config.
#
# File data can be cached in the kernel and/or user caches. User cache can be
# memory and/or file backed.
# Memory backed caches are controlled using cache.data.* configs, while
# file backed cache are controlled using filecache.* configs.
#
readahead_kb: 16384
cache.readdir.kernel.enable: true
cache.readdir.user.enable: true
cache.data.kernel.enable: true
cache.data.user.enable: true
cache.data.user.max_size_mb: 4096

filecache.enable: false
filecache.cachedir: /mnt
filecache.max_size_gb: 1000
cache_max_mb: 4096
