# BlobFuse Nightly Build-Sanity Pipeline

# Run this Pipeline whenever any change happens in selected branch
trigger:
- master

schedules:
  # Cron string < minute hour day-of-month month day-of-week>
  #             * means all like '*' in day of month means everyday
  # Run only on master branch
  # 'always' controls whether to run only if there is a change or not
- cron: "0 0 * * *"
  displayName: Daily midnight BlobFuse build
  branches:
    include:
    - master
  always: true


# List of jobs to run in parallel
jobs:
  - job: Ubuntu_Build 

    # Define on what all OS we want to run this Pipeline
    strategy:
      matrix:
        Ubuntu-16:
          imageName: 'ubuntu-16.04'
        Ubuntu-18:
          imageName: 'ubuntu-18.04' 
    pool:
      vmImage: $(imageName)

    # Each job has set of steps to be done
    steps:
    - script: |
        sudo apt-get install pkg-config cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ -y
      displayName: "Basic Setup"

    - script: |
        sudo sudo apt-get install libfuse-dev -y
      displayName: "libFuse Setup"

    - script: |
        sudo chmod +x build.sh
        . ./build.sh
      displayName: "Build BlobFuse"

    - script: |
        ./build/blobfuse --version
      displayName: "Test the binary"
    
    
