# BlobFuse Nightly Sanity Pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build    
    steps:
    - script: |
        sudo apt-get install pkg-config cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ -y
      displayName: "Basic Setup"
    - script: |
        sudo sudo apt-get install libfuse-dev -y
      displayName: "libFuse Setup"
    - script: |
        sudo chmod +x build.sh
        . ./build.sh
      displayName: "Build BlobFuse"
    
    
