variables:
  tags: 'fuse3'
  depends: 'fuse3'

parameters:
  - name: tag
    displayName: 'New Release Tag'
    type: string
    default: 'blobfuse2-'

  - name: unit_test
    displayName: 'Execute Unit Tests'
    type: boolean
    default: false

  - name: post_release
    displayName: 'Post Release on Github'
    type: boolean
    default: false

  - name: publish_artifacts
    displayName: 'Publish Artifacts to Linux Repos'
    type: boolean
    default: false

  - name: draft
    displayName: 'Post as Draft Release'
    type: boolean
    default: false

  - name: prerelease
    displayName: 'Post as PreRelease'
    type: boolean
    default: false

  - name: update_version
    displayName: 'Update Version'
    type: boolean
    default: false

# Do not trigger this pipeline automatically
trigger: none
pr: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    # authenticatedContainerRegistries:
    # - registry: onebranch.azurecr.io
    #   tenant: AME
    #   identity: 1ESPipelineIdentity
    # containers:
    #   default_linux_container:
    #     image: mcr.microsoft.com/dotnet/sdk:6.0-focal
    # The SDL Source analysis stage can only run in a windows environment due to limitations of Guardian tools. 
    # If you use Linux pool, we require an additional windows image in your pool to run the source analysis.
    sdl:   
      sourceAnalysisPool:
        name: blobfuse2-pool  # Name of your hosted pool
        image: windows2022-1espt
        os: windows  # OS of the image. Allowed values: windows, linux, macOS

    stages:
    - stage: BuildArtifacts
      jobs:
      - job: Set_1
        timeoutInMinutes: 120
        pool:
          name: blobfuse2-pool
          image: ubuntu22-1espt
          os: linux
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: $(Build.ArtifactStagingDirectory)/blobfuse2-temp
            artifactName: 'blobfuse2-linux-unsigned'
            displayName: 'Publish Artifacts'

        # Job strategy is not supported in the 1ES pipeline template. Refer https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/faqs#:~:text=Unfortunately%2C%20it%20is%20not%20possible%20to%20use%20job%20strategy%20to%20specify%20pool%20at%20the%20pipeline.

        variables:
          - group: NightlyBlobFuse
          - name: root_dir
            value: '$(System.DefaultWorkingDirectory)'
          - name: work_dir
            value: '$(System.DefaultWorkingDirectory)/azure-storage-fuse'
          - name: unsigned
            value: '$(Build.ArtifactStagingDirectory)/blobfuse2-temp'
        
        steps:
        - checkout: none
        - script: |
            git clone https://github.com/Azure/azure-storage-fuse
          displayName: 'Checkout Code'
          workingDirectory: $(root_dir)
          
        # list commits from past 12hrs
        - script: |
            git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
            git --no-pager log --since="12 hours ago" --stat
          displayName: 'List Commits'
          workingDirectory: $(work_dir)
          
        # install dependencies required for compiling blobfuse
        - script: |
            sudo apt-get update --fix-missing
            sudo apt-get install ruby-dev build-essential pkg-config cmake gcc g++ rpm $(fuselib) -y
            sudo gem install dotenv -v 2.8.1
            sudo gem install fpm -V
          displayName: "Installing Dependencies"

        # get glibc version with which build is done
        #TODO:: downgrade to fuse2 glibc version
        - script: |
            ldd --version
          displayName: "GLIBC Version"

        # build blobfuse2 and generate binary
        - template: azure-pipeline-templates/build-release.yml@self
          parameters:
            work_dir: $(work_dir)
            root_dir: $(root_dir)
            unit_test: ${{ parameters.unit_test }}
            tags: 'fuse3'
            container: "test-cnt-ubn-22"

        # place the generated binary files & any additional files in appropriate locations
        - script: |
            mkdir -p pkgDir/usr/bin/
            mkdir -p pkgDir/usr/share/blobfuse2/
            cp azure-storage-fuse/blobfuse2 pkgDir/usr/bin/blobfuse2
            cp azure-storage-fuse/bfusemon pkgDir/usr/bin/bfusemon
            cp azure-storage-fuse/setup/baseConfig.yaml pkgDir/usr/share/blobfuse2/
            cp azure-storage-fuse/sampleFileCacheConfig.yaml pkgDir/usr/share/blobfuse2/
            mkdir -p pkgDir/etc/rsyslog.d
            mkdir -p pkgDir/etc/logrotate.d
            cp azure-storage-fuse/setup/11-blobfuse2.conf pkgDir/etc/rsyslog.d
            cp azure-storage-fuse/setup/blobfuse2-logrotate pkgDir/etc/logrotate.d/blobfuse2
          workingDirectory: $(root_dir)
          displayName: 'Accumulate pkg files'
        
        # using fpm tool for packaging of our binary & performing post-install operations
        # for additional information about fpm refer https://fpm.readthedocs.io/en/v1.13.1/
        - script: |
            fpm -s dir -t deb -n blobfuse2 -C pkgDir/ -v `./pkgDir/usr/bin/blobfuse2 --version | cut -d " " -f 3` -d fuse3 \
            --maintainer "Blobfuse v-Team <blobfusevteam@microsoft.com>" --url "https://github.com/Azure/azure-storage-fuse" \
            --description "An user-space filesystem for interacting with Azure Storage" 
            mv ./blobfuse2*.deb ./blobfuse2-`./pkgDir/usr/bin/blobfuse2 --version | cut -d " " -f 3`-$(tags).x86_64.deb
            cp ./blobfuse2*.deb $(unsigned)
          workingDirectory: $(root_dir)
          displayName: 'Make deb Package'

        - script: |
            fpm -s dir -t rpm -n blobfuse2 --rpm-digest sha256 -C pkgDir/ -v `./pkgDir/usr/bin/blobfuse2 --version | cut -d " " -f 3` -d $(depends) \
            --maintainer "Blobfuse v-Team <blobfusevteam@microsoft.com>" --url "https://github.com/Azure/azure-storage-fuse" \
            --description "An user-space filesystem for interacting with Azure Storage" 
            mv ./blobfuse2*.rpm ./blobfuse2-`./pkgDir/usr/bin/blobfuse2 --version | cut -d " " -f 3`-$(tags).x86_64.rpm
            cp ./blobfuse2*.rpm $(unsigned)
          workingDirectory: $(root_dir)
          displayName: 'Make rpm Package'

      - job: Set_2_ARM
        timeoutInMinutes: 120
        pool:
          name: blobfuse2-arm-pool
          image: ubn22armblobfuse-1espt
          os: linux
          hostArchitecture: Arm64
        templateContext:
          outputs:
            - output: pipelineArtifact
              targetPath: $(Build.ArtifactStagingDirectory)/blobfuse2-temp
              artifactName: 'blobfuse2-linux-arm-unsigned'
              displayName: 'Publish Artifacts'

        variables:
          - group: NightlyBlobFuse
          - name: root_dir
            value: '$(System.DefaultWorkingDirectory)'
          - name: work_dir
            value: '$(System.DefaultWorkingDirectory)/azure-storage-fuse'
          - name: unsigned
            value: '$(Build.ArtifactStagingDirectory)/blobfuse2-temp'
        
        steps:
        - checkout: none
        - script: |
            git clone https://github.com/Azure/azure-storage-fuse
          displayName: 'Checkout Code'
          workingDirectory: $(root_dir)
        
        # list commits from past 12hrs
        - script: |
            git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
            git --no-pager log --since="12 hours ago" --stat
          displayName: 'List Commits'
          workingDirectory: $(work_dir)
        
        # install dependencies required for compiling blobfuse
        - script: |
            sudo apt-get update --fix-missing
            sudo apt-get install ruby-dev build-essential pkg-config cmake gcc g++ rpm $(fuselib) -y
            sudo gem install fpm -V
          displayName: "Installing Dependencies"

        # get glibc version with which build is done
        - script: |
            ldd --version
          displayName: "GLIBC Version"

        # build blobfuse2 and generate binary
        - template: 'azure-pipeline-templates/build-release.yml@self'
          parameters:
            work_dir: $(work_dir)
            root_dir: $(root_dir)
            unit_test: ${{ parameters.unit_test }}
            tags: $(tags)
            container: "test-cnt-ubn-22-arm"

        # place the generated binary files & any additional files in appropriate locations
        - script: |
            mkdir -p pkgDir/usr/bin/
            mkdir -p pkgDir/usr/share/blobfuse2/
            cp azure-storage-fuse/blobfuse2 pkgDir/usr/bin/blobfuse2
            cp azure-storage-fuse/bfusemon pkgDir/usr/bin/bfusemon
            cp azure-storage-fuse/setup/baseConfig.yaml pkgDir/usr/share/blobfuse2/
            cp azure-storage-fuse/sampleFileCacheConfig.yaml pkgDir/usr/share/blobfuse2/
            cp azure-storage-fuse/sampleStreamingConfig.yaml pkgDir/usr/share/blobfuse2/
            mkdir -p pkgDir/etc/rsyslog.d
            mkdir -p pkgDir/etc/logrotate.d
            cp azure-storage-fuse/setup/11-blobfuse2.conf pkgDir/etc/rsyslog.d
            cp azure-storage-fuse/setup/blobfuse2-logrotate pkgDir/etc/logrotate.d/blobfuse2
          workingDirectory: $(root_dir)
          displayName: 'Accumulate pkg files'
        
        # using fpm tool for packaging of our binary & performing post-install operations
        # for additional information about fpm refer https://fpm.readthedocs.io/en/v1.13.1/
        - script: |
            fpm -s dir -t deb -n blobfuse2 -C pkgDir/ -v `./pkgDir/usr/bin/blobfuse2 --version | cut -d " " -f 3` -d $(depends) \
            --maintainer "Blobfuse v-Team <blobfusevteam@microsoft.com>" --url "https://github.com/Azure/azure-storage-fuse" \
            --description "An user-space filesystem for interacting with Azure Storage" 
            mv ./blobfuse2*.deb ./blobfuse2-`./pkgDir/usr/bin/blobfuse2 --version | cut -d " " -f 3`-$(tags).arm64.deb
            cp ./blobfuse2*.deb $(unsigned)
          workingDirectory: $(root_dir)
          displayName: 'Make deb Package'

        - script: |
            fpm -s dir -t rpm -n blobfuse2 --rpm-digest sha256 -C pkgDir/ -v `./pkgDir/usr/bin/blobfuse2 --version | cut -d " " -f 3` -d $(depends) \
            --maintainer "Blobfuse v-Team <blobfusevteam@microsoft.com>" --url "https://github.com/Azure/azure-storage-fuse" \
            --description "An user-space filesystem for interacting with Azure Storage" 
            mv ./blobfuse2*.rpm ./blobfuse2-`./pkgDir/usr/bin/blobfuse2 --version | cut -d " " -f 3`-$(tags).aarch64.rpm
            cp ./blobfuse2*.rpm $(unsigned)
          workingDirectory: $(root_dir)
          displayName: 'Make rpm Package'
          
  # BuildArtifacts end here

    - stage: SignArtifacts
      dependsOn: BuildArtifacts
      condition: succeeded('BuildArtifacts')
      jobs:
      - job: SignBlobfuse
        timeoutInMinutes: 120
        pool:
          name: blobfuse2-pool
          image: ubuntu22-1espt
          os: linux

        # download artifacts that need to be published
        templateContext:
          inputs:
          - input: pipelineArtifact
            artifactName: 'blobfuse2-linux-unsigned'
            targetPath: $(Build.ArtifactStagingDirectory)/amd64
            displayName: 'Download Artifacts'
          - input: pipelineArtifact
            artifactName: 'blobfuse2-linux-arm-unsigned'
            targetPath: $(Build.ArtifactStagingDirectory)/arm64
            displayName: 'Download Artifacts'
          outputs:
          - output: pipelineArtifact
            targetPath: $(System.DefaultWorkingDirectory)/blobfuse2-signed
            artifactName: 'blobfuse2-linux-signed'
            displayName: 'Publish Signed Artifacts'

        variables:
          - group: NightlyBlobFuse
          - name: amd64
            value: $(Build.ArtifactStagingDirectory)/amd64
          - name: arm64
            value: $(Build.ArtifactStagingDirectory)/arm64
          - name: mariner
            value: $(Build.ArtifactStagingDirectory)/mariner
          - name: signed
            value: $(Build.ArtifactStagingDirectory)/signed

        steps:
        - checkout: none
        
        - script: |
            echo ${{ parameters.tag }}
          displayName: 'Tag Name'
        
        - script: |
            sudo ls -lRt $(Build.ArtifactStagingDirectory)
            md5sum $(Build.ArtifactStagingDirectory)/amd64/*.deb
            md5sum $(Build.ArtifactStagingDirectory)/amd64/*.rpm
            md5sum $(Build.ArtifactStagingDirectory)/arm64/*.deb
            md5sum $(Build.ArtifactStagingDirectory)/arm64/*.rpm
          displayName: 'List Artifacts'

        - script: |
            mkdir -p $(mariner) && chmod 755 $(mariner)
            cp $(amd64)/*-fuse3*.rpm $(mariner)
            sudo ls -lRt $(mariner)
            md5sum $(mariner)/*
          displayName: 'Copy artifacts for Mariner'
          workingDirectory: $(Build.ArtifactStagingDirectory)
        
        - script: |
            sudo apt-get update -y
            wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb 
            sudo dpkg -i packages-microsoft-prod.deb 
            sudo apt update -y
            sudo apt install apt-transport-https -y
            sudo apt install dotnet-sdk-3.1 -y
          displayName: "Update dependencies"
          
        - template: azure-pipeline-templates/esrp_sign_linux.yml@self
          parameters:
            FolderPath: '$(Build.ArtifactStagingDirectory)/amd64'
            ESRP_AZCOPY_KEY_CODE: $(ESRP_AZCOPY_KEY_CODE)
            Pattern: '*.rpm, *.deb'
            DisplayName: 'ESRP CodeSigning blobfuse2 linux amd64'

        - template: azure-pipeline-templates/esrp_sign_linux.yml@self
          parameters:
            FolderPath: '$(Build.ArtifactStagingDirectory)/arm64'
            ESRP_AZCOPY_KEY_CODE: $(ESRP_AZCOPY_KEY_CODE)
            Pattern: '*.rpm, *.deb'
            DisplayName: 'ESRP CodeSigning blobfuse2 linux arm64'

        - template: azure-pipeline-templates/esrp_sign_linux.yml@self
          parameters:
            FolderPath: '$(mariner)'
            ESRP_AZCOPY_KEY_CODE: $(ESRP_AZCOPY_KEY_CODE)
            Pattern: '*.rpm'
            DisplayName: 'ESRP CodeSigning blobfuse2 mariner'

        # Validate signed images have md5sum changed
        - script: |
            chmod 755 $(Build.ArtifactStagingDirectory)/amd64/*.rpm
            chmod 755 $(Build.ArtifactStagingDirectory)/amd64/*.deb
            chmod 755 $(Build.ArtifactStagingDirectory)/arm64/*.rpm
            chmod 755 $(Build.ArtifactStagingDirectory)/arm64/*.deb
            chmod 755 $(Build.ArtifactStagingDirectory)/mariner/*.rpm
            rm -rf $(Build.ArtifactStagingDirectory)/amd64/*.md
            rm -rf $(Build.ArtifactStagingDirectory)/arm64/*.md
            rm -rf $(Build.ArtifactStagingDirectory)/mariner/*.md
            mv $(Build.ArtifactStagingDirectory)/amd64/* $(Build.ArtifactStagingDirectory)/
            mv $(Build.ArtifactStagingDirectory)/arm64/* $(Build.ArtifactStagingDirectory)/
            mv $(Build.ArtifactStagingDirectory)/mariner/* $(Build.ArtifactStagingDirectory)/
            rm -rf $(Build.ArtifactStagingDirectory)/amd64/
            rm -rf $(Build.ArtifactStagingDirectory)/arm64/
            rm -rf $(Build.ArtifactStagingDirectory)/mariner/
          displayName: 'Make Artifacts executable'

        - script: |
            sudo ls -lRt $(Build.ArtifactStagingDirectory)
            md5sum $(Build.ArtifactStagingDirectory)/amd64/*.deb
            md5sum $(Build.ArtifactStagingDirectory)/arm64/*.rpm
            md5sum $(Build.ArtifactStagingDirectory)/mariner/*
          displayName: 'List Signed Artifacts'
# SignArtifacts end here
