# Blobfuse2 Nightly Build Pipeline

schedules:
  # Cron string < minute hour day-of-month month day-of-week>
  #             * means all, for example '*' in day of month means everyday
  # Run only on main branch
  # 'always' controls whether to run only if there is a change or not
  # Run this pipeline every 15:00 time
  - cron: '0 15 * * *'
    displayName: 'Daily midnight Blobfuse2 build'
    branches:
      include:
        - main

parameters:
  # - name: exhaustive_test
  #   # Quick test or an exhaustive test
  #   displayName: 'Exhaustive test'
  #   type: boolean
  #   default: true
  
  # - name: proxy_test
  # # Proxy tests
  #   displayName: 'Proxy test'
  #   type: boolean
  #   default: true

  # - name: msi_test
  #   # MSI auth based test suites to be run or not
  #   displayName: 'MSI test'
  #   type: boolean
  #   default: true

  # - name: quick_stress
  #   displayName: 'Quick Stress'
  #   type: boolean
  #   default: true
  
  - name: verbose_log
    displayName: 'Verbose Log'
    type: boolean
    default: false

jobs:
  # RHEL Tests
  - job: Set_1
    strategy:
      matrix:
        RHEL-7.9:
          DistroVer: "RHEL-7.9"
          Description: "Red Hat Enterprise Linux 7.9"
          AgentName: "blobfuse-rhel7_9"
          ContainerName: "test-cnt-rhel-7.9"
        RHEL-8:
          DistroVer: "RHEL-8"
          Description: "Red Hat Enterprise Linux 8"
          AgentName: "blobfuse-rhel8"
          containerName: "test-cnt-rhel-8"

    pool:
      name: "blobfuse-rhel-pool"
      demands:
        - ImageOverride -equals $(AgentName)

    variables:
      - group: NightlyBlobFuse
      - name: ROOT_DIR
        value: "/usr/pipeline/workv2"
      - name: WORK_DIR
        value: "/usr/pipeline/workv2/go/src/azure-storage-fuse"
      - name: skipComponentGovernanceDetection
        value: true
      - name: MOUNT_DIR
        value: "/usr/pipeline/workv2/blob_mnt"
      - name: TEMP_DIR
        value: "/usr/pipeline/workv2/temp"
      - name: BLOBFUSE2_CFG
        value: "/usr/pipeline/workv2/blobfuse2.yaml"
      - name: BLOBFUSE2_ADLS_CFG
        value: "/home/vsts/workv2/blobfuse2.adls.yaml"
      - name: GOPATH
        value: "/usr/pipeline/workv2/go"

    steps:
      # Go tool installer
      - task: GoTool@0
        inputs:
          version: '1.16.2'
        displayName: "Install Go Version"

      - template: 'azure-pipeline-templates/distro-tests.yml'
        parameters:
          working_dir: $(WORK_DIR)
          root_dir: $(ROOT_DIR)
          temp_dir: $(TEMP_DIR)
          mount_dir: $(MOUNT_DIR)
          config_path: $(BLOBFUSE2_CFG)
          container: $(ContainerName)
          blob_account_name: $(NIGHTLY_STO_BLOB_ACC_NAME)
          blob_account_key: $(NIGHTLY_STO_BLOB_ACC_KEY)
          adls_account_name: $(AZTEST_ADLS_ACC_NAME)
          adls_account_key: $(AZTEST_ADLS_KEY)
          distro_name: $(AgentName)
          gopath: $(GOPATH) 
          installStep:
            script: |
              sudo yum update -y
              sudo yum install git fuse fuse3 fuse3-devel -y
              sudo yum groupinstall "Development Tools" -y
              sudo yum install python36 -y
            displayName: 'Install fuse'
          verbose_log: ${{ parameters.verbose_log }}

  # Centos Tests
  - job: Set_2
    strategy:
      matrix:
        CentOS-7.9:
          DistroVer: "CentOS-7.9"
          Description: "CentOS 7.9"
          AgentName: "blobfuse-centos7"
          ContainerName: "test-cnt-cent-7"
        CentOS-8.5:
          DistroVer: "CentOS-8.5"
          Description: "CentOS 8.5"
          AgentName: "blobfuse-centos8"
          ContainerName: "test-cnt-cent-8"

    pool:
      name: "blobfuse-centos-pool"
      demands:
        - ImageOverride -equals $(AgentName)

    variables:
      - group: NightlyBlobFuse
      - name: ROOT_DIR
        value: "/usr/pipeline/workv2"
      - name: WORK_DIR
        value: "/usr/pipeline/workv2/go/src/azure-storage-fuse"
      - name: skipComponentGovernanceDetection
        value: true
      - name: MOUNT_DIR
        value: "/usr/pipeline/workv2/blob_mnt"
      - name: TEMP_DIR
        value: "/usr/pipeline/workv2/temp"
      - name: BLOBFUSE2_CFG
        value: "/usr/pipeline/workv2/blobfuse2.yaml"
      - name: BLOBFUSE2_ADLS_CFG
        value: "/home/vsts/workv2/blobfuse2.adls.yaml"
      - name: GOPATH
        value: "/usr/pipeline/workv2/go"

    steps:
      # Go tool installer
      - task: GoTool@0
        inputs:
          version: '1.16.2'
        displayName: "Install Go Version"

      - script: |
          sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sudo sed -i 's|baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        condition: eq(variables['AgentName'], 'blobfuse-centos8')
        displayName: "Update OS mirrors"

      - template: 'azure-pipeline-templates/distro-tests.yml'
        parameters:
          working_dir: $(WORK_DIR)
          root_dir: $(ROOT_DIR)
          temp_dir: $(TEMP_DIR)
          mount_dir: $(MOUNT_DIR)
          config_path: $(BLOBFUSE2_CFG)
          container: $(ContainerName)
          blob_account_name: $(NIGHTLY_STO_BLOB_ACC_NAME)
          blob_account_key: $(NIGHTLY_STO_BLOB_ACC_KEY)
          adls_account_name: $(AZTEST_ADLS_ACC_NAME)
          adls_account_key: $(AZTEST_ADLS_KEY)
          distro_name: $(AgentName)
          gopath: $(GOPATH)
          installStep:
            script: |
              sudo yum update -y --skip-broken
              if [ $(AgentName) == "blobfuse-centos8" ]; then
                sudo yum install gcc gcc-c++ make git fuse fuse3 fuse3-devel python36 -y --nobest --allowerasing
              else
                sudo yum install gcc gcc-c++ make git fuse3 fuse3-devel python36 -y
              fi
            displayName: 'Install fuse'
          verbose_log: ${{ parameters.verbose_log }}

  # Oracle Tests
  - job: Set_3
    strategy:
      matrix:
        Oracle-8.1:
          DistroVer: "Oracle-8.1"
          Description: "Oracle Linux 8.1"
          AgentName: "blobfuse-oracle81"
          ContainerName: "test-cnt-ora-81"

    pool:
      name: "blobfuse-oracle-pool"
      demands:
        - ImageOverride -equals $(AgentName)

    variables:
      - group: NightlyBlobFuse
      - name: ROOT_DIR
        value: "/usr/pipeline/workv2"
      - name: WORK_DIR
        value: "/usr/pipeline/workv2/go/src/azure-storage-fuse"
      - name: skipComponentGovernanceDetection
        value: true
      - name: MOUNT_DIR
        value: "/usr/pipeline/workv2/blob_mnt"
      - name: TEMP_DIR
        value: "/usr/pipeline/workv2/temp"
      - name: BLOBFUSE2_CFG
        value: "/usr/pipeline/workv2/blobfuse2.yaml"
      - name: BLOBFUSE2_ADLS_CFG
        value: "/home/vsts/workv2/blobfuse2.adls.yaml"
      - name: GOPATH
        value: "/usr/pipeline/workv2/go"

    steps:
      # Go tool installer
      - task: GoTool@0
        inputs:
          version: '1.16.2'
        displayName: "Install Go Version"

      - template: 'azure-pipeline-templates/distro-tests.yml'
        parameters:
          working_dir: $(WORK_DIR)
          root_dir: $(ROOT_DIR)
          temp_dir: $(TEMP_DIR)
          mount_dir: $(MOUNT_DIR)
          config_path: $(BLOBFUSE2_CFG)
          container: $(ContainerName)
          blob_account_name: $(NIGHTLY_STO_BLOB_ACC_NAME)
          blob_account_key: $(NIGHTLY_STO_BLOB_ACC_KEY)
          adls_account_name: $(AZTEST_ADLS_ACC_NAME)
          adls_account_key: $(AZTEST_ADLS_KEY)
          distro_name: $(AgentName)
          gopath: $(GOPATH)
          installStep:
            script: |
              sudo yum update -y
              sudo yum install gcc gcc-c++ make git fuse fuse3 fuse3-devel python36 -y --nobest --allowerasing 
            displayName: 'Install fuse'
          verbose_log: ${{ parameters.verbose_log }}

  # Debian Tests
  - job: Set_4
    strategy:
      matrix:
        Debian-9.0:
          DistroVer: "Debian9.0"
          Description: "Debian 9"
          AgentName: "blobfuse-debian9"
          ContainerName: "test-cnt-deb-9"
          fuselib: 'libfuse-dev'
          tags: 'fuse2'
        Debian-10.0:
          DistroVer: "Debian10.0"
          Description: "Debian 10"
          AgentName: "blobfuse-debian10"
          ContainerName: "test-cnt-deb-10"
          fuselib: 'libfuse-dev'
          tags: 'fuse2'
        Debian-11.0:
          DistroVer: "Debian11.0"
          Description: "Debian 11"
          AgentName: "blobfuse-debian11"
          ContainerName: "test-cnt-deb-11"
          fuselib: 'libfuse3-dev'
          tags: 'fuse3'

    pool:
      name: "blobfuse-debian-pool"
      demands:
        - ImageOverride -equals $(AgentName)

    variables:
      - group: NightlyBlobFuse
      - name: ROOT_DIR
        value: "/usr/pipeline/workv2"
      - name: WORK_DIR
        value: "/usr/pipeline/workv2/go/src/azure-storage-fuse"
      - name: skipComponentGovernanceDetection
        value: true
      - name: MOUNT_DIR
        value: "/usr/pipeline/workv2/blob_mnt"
      - name: TEMP_DIR
        value: "/usr/pipeline/workv2/temp"
      - name: BLOBFUSE2_CFG
        value: "/usr/pipeline/workv2/blobfuse2.yaml"
      - name: BLOBFUSE2_ADLS_CFG
        value: "/home/vsts/workv2/blobfuse2.adls.yaml"
      - name: GOPATH
        value: "/usr/pipeline/workv2/go"

    steps:
      # Go tool installer
      - task: GoTool@0
        inputs:
          version: '1.16.2'
        displayName: "Install Go Version"

      - template: 'azure-pipeline-templates/distro-tests.yml'
        parameters:
          working_dir: $(WORK_DIR)
          root_dir: $(ROOT_DIR)
          temp_dir: $(TEMP_DIR)
          mount_dir: $(MOUNT_DIR)
          config_path: $(BLOBFUSE2_CFG)
          container: $(ContainerName)
          blob_account_name: $(NIGHTLY_STO_BLOB_ACC_NAME)
          blob_account_key: $(NIGHTLY_STO_BLOB_ACC_KEY)
          adls_account_name: $(AZTEST_ADLS_ACC_NAME)
          adls_account_key: $(AZTEST_ADLS_KEY)
          distro_name: $(AgentName)
          tags: $(tags)
          fuselib: $(fuselib)
          gopath: $(GOPATH)
          installStep:
            script: |
              sudo apt-get update --fix-missing -y
              sudo apt-get install $(fuselib) -y
              sudo apt-get install build-essential git python3 -y
            displayName: 'Install fuse'
          verbose_log: ${{ parameters.verbose_log }}

  # SUSE Tests
  - job: Set_5
    strategy:
      matrix:
        SUSE-15:
          DistroVer: "SUSE-15"
          Description: "SUSE Enterprise Linux 15"
          AgentName: "blobfuse-suse15"
          ContainerName: "test-cnt-suse-15"

    pool:
      name: "blobfuse-suse-pool"
      demands:
        - ImageOverride -equals $(AgentName)

    variables:
      - group: NightlyBlobFuse
      - name: ROOT_DIR
        value: "/usr/pipeline/workv2"
      - name: WORK_DIR
        value: "/usr/pipeline/workv2/go/src/azure-storage-fuse"
      - name: skipComponentGovernanceDetection
        value: true
      - name: MOUNT_DIR
        value: "/usr/pipeline/workv2/blob_mnt"
      - name: TEMP_DIR
        value: "/usr/pipeline/workv2/temp"
      - name: BLOBFUSE2_CFG
        value: "/usr/pipeline/workv2/blobfuse2.yaml"
      - name: BLOBFUSE2_ADLS_CFG
        value: "/home/vsts/workv2/blobfuse2.adls.yaml"
      - name: GOPATH
        value: "/usr/pipeline/workv2/go"

    steps:
      # Go tool installer
      - task: GoTool@0
        inputs:
          version: '1.16.2'
        displayName: "Install Go Version"

      - template: 'azure-pipeline-templates/distro-tests.yml'
        parameters:
          working_dir: $(WORK_DIR)
          root_dir: $(ROOT_DIR)
          temp_dir: $(TEMP_DIR)
          mount_dir: $(MOUNT_DIR)
          config_path: $(BLOBFUSE2_CFG)
          container: $(ContainerName)
          blob_account_name: $(NIGHTLY_STO_BLOB_ACC_NAME)
          blob_account_key: $(NIGHTLY_STO_BLOB_ACC_KEY)
          adls_account_name: $(AZTEST_ADLS_ACC_NAME)
          adls_account_key: $(AZTEST_ADLS_KEY)
          distro_name: $(AgentName)
          gopath: $(GOPATH)
          installStep:
            script: |
              sudo zypper -n install fuse3 fuse3-devel
            displayName: 'Install fuse'
          verbose_log: ${{ parameters.verbose_log }}

  # Mariner Tests
  - job: Set_6
    strategy:
      matrix:
        Mariner:
          DistroVer: "Mariner"
          Description: "CBL-Mariner Linux"
          AgentName: "blobfuse-mariner"
          ContainerName: "test-cnt-mari-1"
          fuselib: 'libfuse-dev'
          tags: 'fuse2'

    pool:
      name: "blobfuse-mariner-pool"
      demands:
        - ImageOverride -equals $(AgentName)

    variables:
      - group: NightlyBlobFuse
      - name: ROOT_DIR
        value: "/usr/pipeline/workv2"
      - name: WORK_DIR
        value: "/usr/pipeline/workv2/go/src/azure-storage-fuse"
      - name: skipComponentGovernanceDetection
        value: true
      - name: MOUNT_DIR
        value: "/usr/pipeline/workv2/blob_mnt"
      - name: TEMP_DIR
        value: "/usr/pipeline/workv2/temp"
      - name: BLOBFUSE2_CFG
        value: "/usr/pipeline/workv2/blobfuse2.yaml"
      - name: BLOBFUSE2_ADLS_CFG
        value: "/home/vsts/workv2/blobfuse2.adls.yaml"
      - name: GOPATH
        value: "/usr/pipeline/workv2/go"

    steps:
      # Go tool installer
      - task: GoTool@0
        inputs:
          version: '1.16.2'
        displayName: "Install Go Version"

      - template: 'azure-pipeline-templates/distro-tests.yml'
        parameters:
          working_dir: $(WORK_DIR)
          root_dir: $(ROOT_DIR)
          temp_dir: $(TEMP_DIR)
          mount_dir: $(MOUNT_DIR)
          config_path: $(BLOBFUSE2_CFG)
          container: $(ContainerName)
          blob_account_name: $(NIGHTLY_STO_BLOB_ACC_NAME)
          blob_account_key: $(NIGHTLY_STO_BLOB_ACC_KEY)
          adls_account_name: $(AZTEST_ADLS_ACC_NAME)
          adls_account_key: $(AZTEST_ADLS_KEY)
          distro_name: $(AgentName)
          tags: $(tags)
          fuselib: $(fuselib)
          gopath: $(GOPATH)
          installStep:
            script: |
              sudo tdnf install build-essential git fuse fuse-devel python36 -y
            displayName: 'Install fuse'
          verbose_log: ${{ parameters.verbose_log }}