# Blobfuse2 Nightly Build-Sanity Pipeline

# In case of failure on a Self-Hosted Agent perform the following steps to get the vm back online:
# 1. Check which vm is offline by going to agent-pools in Azure pipelines portal
# 2. Log into the VM that is offline
# 3. Clear the _work or work directory which must be in myagent or $(HOME) directory
# 4. Verify whether system is online from the Azure pipelines portal

jobs:
  - job: Coverage
    timeoutInMinutes: 300
    strategy:
      matrix:
        Ubuntu-18:
          AgentName: 'blobfuse-ubuntu18'
          imageName: 'ubuntu-18.04'
          containerName: 'test-cnt-ubn-18'
          fuselib: 'libfuse-dev'
          fuselib2: 'fuse'
          tags: 'fuse2'
        Ubuntu-20:
          AgentName: 'blobfuse-ubuntu20'
          imageName: 'ubuntu-20.04'
          containerName: 'test-cnt-ubn-20'
          fuselib: 'libfuse3-dev'
          fuselib2: 'fuse3'
          tags: 'fuse3'

    pool:
      name: "blobfuse-ubuntu-pool"
      demands:
        - ImageOverride -equals $(AgentName)

    variables:
      - group: NightlyBlobFuse
      - name: MOUNT_DIR
        value: '$(Pipeline.Workspace)/blob_mnt'
      - name: TEMP_DIR
        value: '$(Pipeline.Workspace)/blobfuse2_tmp'
      - name: BLOBFUSE2_CFG
        value: '$(Pipeline.Workspace)/blobfuse2.yaml'
      - name: BLOBFUSE2_STREAM_CFG
        value: '$(Pipeline.Workspace)/blobfuse2_stream.yaml'
      - name: BLOBFUSE2_ADLS_CFG
        value: '$(Pipeline.Workspace)/blobfuse2.adls.yaml'
      - name: GOPATH
        value: '$(Pipeline.Workspace)/go'
      - name: ROOT_DIR
        value: '$(System.DefaultWorkingDirectory)' 
      - name: WORK_DIR
        value: '$(System.DefaultWorkingDirectory)/azure-storage-fuse'

    steps:
      - checkout: none

      # Clone the repo
      - script: |
          git clone https://github.com/Azure/azure-storage-fuse
        displayName: 'Checkout Code'
        workingDirectory: $(ROOT_DIR)

      # Checkout the branch
      - script: |
          git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
        displayName: 'Checkout Branch'
        workingDirectory: $(WORK_DIR)
    
      - script: |
          sudo apt-get update --fix-missing -o Dpkg::Options::="--force-confnew"
          sudo apt-get install make cmake gcc g++ $(fuselib) $(fuselib2) -y -o Dpkg::Options::="--force-confnew"
        displayName: 'Install libfuse'


      # Create directory structure
      - script: |
          sudo mkdir -p $(ROOT_DIR)
          sudo chown -R `whoami` $(ROOT_DIR)
          chmod 777 $(ROOT_DIR)
        displayName: 'Create Directory Structure'

      # -------------------------------------------------------
      # Pull and build the code
      - template: 'azure-pipeline-templates/build.yml'
        parameters:
          working_directory: $(WORK_DIR)
          root_dir: $(Pipeline.Workspace)
          mount_dir: $(MOUNT_DIR)
          temp_dir: $(TEMP_DIR)
          gopath: $(GOPATH)
          container: $(containerName)
          tags: $(tags)
          fuselib: $(fuselib)
          skip_msi: "false"

      # -------------------------------------------------------
      # UT based code coverage test
      - script: |
          go test -v -timeout=1h ./... --tags=unittest,$(tags) -covermode count -coverprofile ./blobfuse2_ut.cov
        workingDirectory: $(WORK_DIR)
        displayName: "UT Code Coverage"
  
      # -------------------------------------------------------
      # Build code coverage binary
      - script: |
          go test -coverpkg="./..." -covermode=count -c --tags=$(tags) -o blobfuse2.test
        workingDirectory: $(WORK_DIR)
        displayName: "Build coverage binary"

      # -------------------------------------------------------
      # Config Generation (Block Blob)
      - script: |
          cd $(WORK_DIR)
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/blobfuse2_gentest1.cov gen-test-config --config-file=azure_key.yaml --container-name=$(containerName) --temp-path=$(TEMP_DIR) --output-file=$(BLOBFUSE2_CFG)
        env:
          NIGHTLY_STO_ACC_NAME: $(NIGHTLY_STO_BLOB_ACC_NAME)
          NIGHTLY_STO_ACC_KEY: $(NIGHTLY_STO_BLOB_ACC_KEY)
          ACCOUNT_TYPE: 'block'
          ACCOUNT_ENDPOINT: 'https://$(NIGHTLY_STO_BLOB_ACC_NAME).blob.core.windows.net'
          VERBOSE_LOG: false
        displayName: 'Create Config File - Block Blob'
        workingDirectory: $(WORK_DIR)
        continueOnError: false
      
      # Code Coverage with e2e-tests for block blob
      - script: |
          rm -rf $(MOUNT_DIR)/*
          rm -rf $(TEMP_DIR)/*
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/blobfuse2_block.cov mount $(MOUNT_DIR) --config-file=$(BLOBFUSE2_CFG) --foreground=true &
          sleep 10
          ps -aux | grep blobfuse2
          rm -rf $(MOUNT_DIR)/*
          cd test/e2e_tests
          go test -v -timeout=7200s ./... -args -mnt-path=$(MOUNT_DIR) -tmp-path=$(TEMP_DIR)
          cd -
          sudo fusermount -u $(MOUNT_DIR) 
          sleep 5
        workingDirectory: $(WORK_DIR)
        displayName: "Block Blob Coverage"

      - script: |
          cd $(WORK_DIR)
          $(WORK_DIR)/blobfuse2 gen-test-config --config-file=azure_key.yaml --container-name=$(containerName) --temp-path=$(TEMP_DIR) --output-file=$(BLOBFUSE2_ADLS_CFG)
        env:
          NIGHTLY_STO_ACC_NAME: $(AZTEST_ADLS_ACC_NAME)
          NIGHTLY_STO_ACC_KEY:  $(AZTEST_ADLS_KEY)
          ACCOUNT_TYPE: 'adls'
          ACCOUNT_ENDPOINT: 'https://$(AZTEST_ADLS_ACC_NAME).dfs.core.windows.net'
          VERBOSE_LOG: false
        displayName: 'Create Config File - ADLS'
        continueOnError: false

      # Code Coverage with e2e-tests for adls blob
      - script: |
          rm -rf $(MOUNT_DIR)/*
          rm -rf $(TEMP_DIR)/*
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/blobfuse2_adls.cov mount $(MOUNT_DIR) --config-file=$(BLOBFUSE2_ADLS_CFG) --foreground=true &
          sleep 10
          ps -aux | grep blobfuse2
          rm -rf $(MOUNT_DIR)/*
          cd test/e2e_tests
          go test -v -timeout=7200s ./... -args -mnt-path=$(MOUNT_DIR) -adls=true -tmp-path=$(TEMP_DIR)
          cd -
          ./blobfuse2 unmount all
          sleep 5
        workingDirectory: $(WORK_DIR)
        displayName: "ADLS Coverage"


      # -------------------------------------------------------
      # Config Generation (Block Blob - LFU policy)
      - script: |
          cd $(WORK_DIR)
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/blobfuse2_gentest2.cov gen-test-config --config-file=azure_key_lfu.yaml --container-name=$(containerName) --temp-path=$(TEMP_DIR) --output-file=$(BLOBFUSE2_CFG)
        env:
          NIGHTLY_STO_ACC_NAME: $(NIGHTLY_STO_BLOB_ACC_NAME)
          NIGHTLY_STO_ACC_KEY: $(NIGHTLY_STO_BLOB_ACC_KEY)
          ACCOUNT_TYPE: 'block'
          ACCOUNT_ENDPOINT: 'https://$(NIGHTLY_STO_BLOB_ACC_NAME).blob.core.windows.net'
          VERBOSE_LOG: false
        displayName: 'Create Config File - LFU'
        continueOnError: false
        workingDirectory: $(WORK_DIR)
      
      # Code Coverage with e2e-tests for block blob with lfu policy
      - script: |
          rm -rf $(MOUNT_DIR)/*
          rm -rf $(TEMP_DIR)/*
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/blobfuse2_block_lfu.cov mount $(MOUNT_DIR) --config-file=$(BLOBFUSE2_CFG) --foreground=true &
          sleep 10
          ps -aux | grep blobfuse2
          rm -rf $(MOUNT_DIR)/*
          cd test/e2e_tests
          go test -v -timeout=7200s ./... -args -mnt-path=$(MOUNT_DIR) -tmp-path=$(TEMP_DIR)
          cd -
          ./blobfuse2 unmount $(MOUNT_DIR)
          sleep 5
        workingDirectory: $(WORK_DIR)
        displayName: "Block Blob LFU Coverage"


      # -------------------------------------------------------
      # Config Generation (Block Blob - Stream)
      - script: |
          cd $(WORK_DIR)
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/blobfuse2_gentest3.cov gen-test-config --config-file=azure_stream.yaml --container-name=$(containerName) --temp-path=$(TEMP_DIR) --output-file=$(BLOBFUSE2_STREAM_CFG)
        displayName: 'Create Config File - Stream'
        env:
          NIGHTLY_STO_ACC_NAME: $(NIGHTLY_STO_BLOB_ACC_NAME)
          NIGHTLY_STO_ACC_KEY: $(NIGHTLY_STO_BLOB_ACC_KEY)
          ACCOUNT_TYPE: 'block'
          ACCOUNT_ENDPOINT: 'https://$(NIGHTLY_STO_BLOB_ACC_NAME).blob.core.windows.net'
          VERBOSE_LOG: false
        continueOnError: false
        workingDirectory: $(WORK_DIR)
      
      # Streaming test preparation
      - script: |
          rm -rf $(MOUNT_DIR)/*
          rm -rf $(TEMP_DIR)/*
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/blobfuse2_stream_prep.cov mount $(MOUNT_DIR) --config-file=$(BLOBFUSE2_CFG) --foreground=true &
          sleep 10
          ps -aux | grep blobfuse2
          for i in {10,50,100,200,500,1024}; do echo $i; done | parallel --will-cite -j 5 'head -c {}M < /dev/urandom > $(WORK_DIR)/myfile_{}'
          for i in {10,50,100,200,500,1024}; do echo $i; done | parallel --will-cite -j 5 'cp $(WORK_DIR)/myfile_{} $(MOUNT_DIR)/'
          ./blobfuse2 unmount $(MOUNT_DIR)*
          sudo fusermount -u $(MOUNT_DIR) 
          sleep 5
        workingDirectory: $(WORK_DIR)
        displayName: "Block Blob Stream Preparation"

      # Code Coverage with e2e-tests for block blob with streaming on
      - script: |
          rm -rf $(MOUNT_DIR)/*
          rm -rf $(TEMP_DIR)/*
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/blobfuse2_stream.cov mount $(MOUNT_DIR) --config-file=$(BLOBFUSE2_STREAM_CFG) --foreground=true &
          sleep 10
          ps -aux | grep blobfuse2
          ./blobfuse2 mount list
          for i in {10,50,100,200,500,1024}; do echo $i; done | parallel --will-cite -j 5 'diff $(WORK_DIR)/myfile_{} $(MOUNT_DIR)/myfile_{}' 
          sudo fusermount -u $(MOUNT_DIR) 
          sleep 5
        workingDirectory: $(WORK_DIR)
        displayName: "Block Blob Stream Coverage"


      # -------------------------------------------------------
      # Config Generation (Block Blob) for cli options
      - script: |
          cd $(WORK_DIR)
          $(WORK_DIR)/blobfuse2 gen-test-config --config-file=azure_key.yaml --container-name=$(containerName) --temp-path=$(TEMP_DIR) --output-file=$(BLOBFUSE2_CFG)
        displayName: 'Create Config File - Block Blob'
        env:
          NIGHTLY_STO_ACC_NAME: $(NIGHTLY_STO_BLOB_ACC_NAME)
          NIGHTLY_STO_ACC_KEY: $(NIGHTLY_STO_BLOB_ACC_KEY)
          ACCOUNT_TYPE: 'block'
          ACCOUNT_ENDPOINT: 'https://$(NIGHTLY_STO_BLOB_ACC_NAME).blob.core.windows.net'
          VERBOSE_LOG: false

      # Component generation code coverage
      - script: |
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/generate_cmd.cov generate test_component
          if [ $? -ne 0 ]; then
            exit 1
          fi
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : Component Generation"

      # Mount / Unmount / List code coverage
      - script: |
          rm -rf $(MOUNT_DIR)/*
          rm -rf $(TEMP_DIR)/*

          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/list_empty_cmd.cov mount list
          if [ $? -ne 0 ]; then
            exit 1
          fi
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : Mount List"

      - script: |
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/mount_cmd.cov mount all $(MOUNT_DIR) --config-file=$(BLOBFUSE2_CFG) --log-level=log_debug 
          if [ $? -ne 0 ]; then
            exit 1
          fi

          sleep 20     

          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/list_cmd_all.cov mount list
          if [ $? -ne 0 ]; then
            exit 1
          fi
          ./blobfuse2 unmount all
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : Mount all and List"

      - script: |
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/mount_cmd_all.cov mount all $(MOUNT_DIR) --config-file=$(BLOBFUSE2_CFG) --log-level=log_debug 
          if [ $? -ne 0 ]; then
            exit 1
          fi

          sleep 20    
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/umnt_cmd_cont.cov unmount $(MOUNT_DIR)/$(containerName)
          if [ $? -ne 0 ]; then
            exit 1
          fi

          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/umnt_wild_cmd.cov unmount testmut*
          if [ $? -ne 0 ]; then
            exit 1
          fi

          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/umnt_negative_cmd.cov unmount abcdef
          if [ $? -ne 0 ]; then
            exit 1
          fi

          for i in {1..5}; do ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/umnt_all_cmd.cov unmount all; done
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : Unmount options"


      # Mount / Unmount Negative tests
      - script: |
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/mount_neg.cov mount all /abc --config-file=$(BLOBFUSE2_CFG) --log-level=log_debug
          if [ $? -eq 0 ]; then
            exit 1
          fi
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : Invalid mount path"
        timeoutInMinutes: 2

      - script: |
          ./blobfuse2 unmount all
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/mount_foreg.cov mount $(MOUNT_DIR) --config-file=$(BLOBFUSE2_CFG) --log-level=log_debug --foreground=true &
          if [ $? -ne 0 ]; then
            exit 1
          fi

          sleep 5

          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/mount_remount.cov mount $(MOUNT_DIR) --config-file=$(BLOBFUSE2_CFG) --log-level=log_debug
          if [ $? -eq 0 ]; then
            exit 1
          fi

          sleep 5
          ./blobfuse2 unmount all
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : Remount test"
        timeoutInMinutes: 2

      # Doc generation tests
      - script: |
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/doc1.cov doc
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/doc2.cov doc --output-location /notexists
          touch ~/a.txt
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/doc2.cov doc --output-location ~/a.txt
          rm -rf ~/a.txt
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : doc generation"
        timeoutInMinutes: 2

      # Version check
      - script: |
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/version1.cov --version
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/version2.cov version
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/version2.cov version --check
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : doc generation"
        timeoutInMinutes: 2

      # Simulate config change
      - script: |
          rm -rf $(MOUNT_DIR)/*
          rm -rf $(TEMP_DIR)/*
          ./blobfuse2 unmount all
          
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/mount_foreg_2.cov mount all $(MOUNT_DIR) --config-file=$(BLOBFUSE2_CFG) --log-level=log_debug --foreground=true &
          if [ $? -ne 0 ]; then
            exit 1
          fi

          sleep 5
          echo -e "\n\nlogging:\n  level:log_debug\n  type:base" >> $(BLOBFUSE2_CFG)
          sed -i 's/timeout:.*/timeout: 300/' $(BLOBFUSE2_CFG)
          sleep 5

          ./blobfuse2 unmount all
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : Config change simulator"

      # Secure Config, fine to use insecure passphrase as this is just for testing
      - script: |
          rm -rf $(MOUNT_DIR)/*
          rm -rf $(TEMP_DIR)/*
          ./blobfuse2 unmount all
          ./blobfuse2 gen-test-config --config-file=azure_key.yaml --container-name=$(containerName) --temp-path=$(TEMP_DIR) --output-file=$(BLOBFUSE2_CFG)
          
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/secure_encrypt.cov secure encrypt --config-file=$(BLOBFUSE2_CFG) --output-file=$(Pipeline.Workspace)/blobfuse2.azsec --passphrase=123123123123123123123123 
          if [ $? -ne 0 ]; then
            exit 1
          fi
          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/mount_secure.cov mount $(MOUNT_DIR) --config-file=$(Pipeline.Workspace)/blobfuse2.azsec --passphrase=123123123123123123123123 &
          sleep 10
          ps -aux | grep blobfuse2
          rm -rf $(MOUNT_DIR)/*
          cd test/e2e_tests
          go test -v -timeout=7200s ./... -args -mnt-path=$(MOUNT_DIR) -adls=true -tmp-path=$(TEMP_DIR)
          cd -

          ./blobfuse2.test -test.v -test.coverprofile=$(WORK_DIR)/secure_set.cov secure set --config-file=$(Pipeline.Workspace)/blobfuse2.azsec --passphrase=123123123123123123123123 --key=logging.level --value=log_debug
          ./blobfuse2 unmount all
          sleep 5
        workingDirectory: $(WORK_DIR)
        displayName: "CLI : Secure Config"

      # -------------------------------------------------------
      # Coverage report consolidation
      - script: |
          echo 'mode: count' > ./blobfuse2_coverage_raw.rpt
          tail -q -n +2 ./*.cov >> ./blobfuse2_coverage_raw.rpt
          cat ./blobfuse2_coverage_raw.rpt  | grep -v mock_component | grep -v base_component | grep -v loopback | grep -v "common/log" | grep -v "common/exectime" > ./blobfuse2_coverage.rpt 
          go tool cover -func blobfuse2_coverage.rpt  > ./blobfuse2_func_cover.rpt
          go tool cover -html=./blobfuse2_coverage.rpt -o ./blobfuse2_coverage.html
          go tool cover -html=./blobfuse2_ut.cov -o ./blobfuse2_ut.html
          cp ./*.rpt  $(Build.ArtifactStagingDirectory)/
          cp ./*.cov  $(Build.ArtifactStagingDirectory)/
          cp ./*.html $(Build.ArtifactStagingDirectory)/
        workingDirectory: $(WORK_DIR)
        displayName: "Save coverage report"

      # Publish the Artifacts
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'Blobfuse2 Coverage $(tags)'
        displayName: 'Publish Artifacts for blobfuse2 code coverage'
        condition: succeeded()

      # Overall code coverage check
      - script: |
          chmod 777 ./test/scripts/coveragecheck.sh
          ./test/scripts/coveragecheck.sh
        workingDirectory: $(WORK_DIR)
        displayName: "Overall coverage check"

      # File level code coverage check
      - script: |
          ./test/scripts/coveragecheck.sh file
        workingDirectory: $(WORK_DIR)
        displayName: "File level coverage check"
        condition: always()
  