# Blobfuse2 Nightly Build Pipeline

schedules:
  # Cron string < minute hour day-of-month month day-of-week>
  #             * means all, for example '*' in day of month means everyday
  # Run only on main branch
  # 'always' controls whether to run only if there is a change or not
  # Run this pipeline every 15:00 time
  - cron: '0 15 * * *'
    displayName: 'Daily midnight Blobfuse2 build'
    branches:
      include:
        - main

jobs:

  - job: Set_1
    pool:
      name: "blobfuse-rhel-pool"
      # demands:
      #   - Agent.Name -equals RHEL 7.5

    steps:
      - checkout: none
      - script: |
          echo "Hello World"
        displayName: 'Test'