# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- main

jobs:
  # Ubuntu based test suite
  - job: test
    displayName: CI on
    strategy:
      matrix:
        Ubuntu-20:
          AgentName: 'blobfuse-ubuntu20'
          containerName: 'test-cnt-ubn-20'
          fuselib: 'libfuse-dev'
          tags: 'fuse2'
          adlsSas: $(AZTEST_ADLS_CONT_SAS_UBN_20)
        Ubuntu-22:
          AgentName: 'blobfuse-ubuntu22'
          containerName: 'test-cnt-ubn-22'
          fuselib: 'libfuse3-dev'
          tags: 'fuse3'
          adlsSas: $(AZTEST_ADLS_CONT_SAS_UBN_22)
  
    pool:
      name: "blobfuse-ubuntu-pool"
      demands:
        - ImageOverride -equals $(AgentName)

    variables:
      - group: NightlyBlobFuse
      
    steps:
    # ----------------------------------------------------------------
      - template: 'azure-pipeline-templates/blobfuse2-ci-template.yml'
        parameters:
          container: $(containerName)
          tags: $(tags)
          fuselib: $(fuselib)

    
  - job: test_ARM64
    displayName: CI on
    strategy:
      matrix:
        Ubuntu-22-ARM64:
          AgentName: 'blobfuse-ubn22-arm64'
          containerName: 'test-cnt-ubn-22'
          fuselib: 'libfuse3-dev'
          tags: 'fuse3'
          adlsSas: $(AZTEST_ADLS_CONT_SAS_UBN_22)
  
    pool:
      name: "blobfuse-ubn-arm64-pool"
      demands:
        - ImageOverride -equals $(AgentName)
    
    variables:
      - group: NightlyBlobFuse
      
    steps:
    # ----------------------------------------------------------------
      - template: 'azure-pipeline-templates/blobfuse2-ci-template.yml'
        parameters:
          container: $(containerName)
          tags: $(tags)
          fuselib: $(fuselib)  
          skip_fmt: false  
