name: disk-benchmark
description: "Benchmark the disk throughput using FIO"
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to push benchmark results'
    required: true
  ARCH:
    description: 'Architecture of the machine (e.g., x86_64, arm64)'
    required: true

runs:
  using: "composite"

  steps:
    - name: "Get the throughput for the disk"
      shell: bash
      run: |
        sudo mkdir -p /mnt/localssd
        sudo chmod 777 /mnt/localssd
        sudo mkdir disk
        sudo chmod 777 disk
        set -euo pipefail
        # Run FIO sequential write test to get the bandwidth of the disk
        fio --name=sequential-write \
            --ioengine=libaio \
            --direct=1 \
            --rw=write \
            --bs=1M \
            --size=4G \
            --iodepth=64 \
            --numjobs=4 \
            --runtime=60 \
            --group_reporting \
            --output-format=json \
            --filename=/mnt/localssd/fiotest.tmp | \
        jq '[{
              name: "sequential_write_directio",
              value: (.jobs[0].write.bw / 1024),
              unit: "MiB/s"
            }]' > ./disk/write.json

        # Run FIO sequential read test to get the bandwidth of the disk
        fio --name=sequential-read-disk \
            --ioengine=libaio \
            --direct=1 \
            --rw=read \
            --bs=1M \
            --size=4G \
            --iodepth=64 \
            --numjobs=4 \
            --runtime=60 \
            --group_reporting \
            --output-format=json \
            --filename=/mnt/localssd/fiotest.tmp | \
        jq '[{
              name: "sequential_read_directio",
              value: (.jobs[0].read.bw / 1024),
              unit: "MiB/s"
            }]' > ./disk/read.json

        rm /mnt/localssd/fiotest.tmp
        cat ./disk/write.json
        cat ./disk/read.json

    - name: "Update Write throughput Results for Disk"
      # if: github.event_name != 'workflow_dispatch'
      uses: benchmark-action/github-action-benchmark@v1
      with:
        output-file-path: disk/write.json
        tool: 'customBiggerIsBetter'
        max-items-in-chart: 100
        github-token: ${{ inputs.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        gh-pages-branch: benchmarks
        benchmark-data-dir-path: ${{ inputs.ARCH }}/disk/write

    - name: "Update Read throughput Results for Disk"
      # if: github.event_name != 'workflow_dispatch'
      uses: benchmark-action/github-action-benchmark@v1
      with:
        output-file-path: disk/read.json
        tool: 'customBiggerIsBetter'
        max-items-in-chart: 100
        github-token: ${{ inputs.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        gh-pages-branch: benchmarks
        benchmark-data-dir-path: ${{ inputs.ARCH }}/disk/read
