# Refer ./setup/baseConfig.yaml for full set of config parameters
allow-other: true

logging:
  type: syslog

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /tmp/blobfuse_temp
  timeout-sec: 0 
  allow-non-empty-temp: true
  cleanup-on-start: true

attr_cache:
  timeout-sec: 7200

   

