name: perftesting
description: "Execute perf testing scripts and generate the pages"

inputs:
  ARCH:
    required: true
    description: "Type of architecture"
  STANDARD_ACCOUNT:
    required: true
    description: "Standard Storage Account"
  STANDARD_KEY:
    required: true
    description: "Standard Storage Account Key"
  PREMIUM_ACCOUNT:
    required: true
    description: "Premium Storage Account"  
  PREMIUM_KEY:  
    required: true
    description: "Premium Storage Account Key"  
  STANDARD_HNS_ACCOUNT:
    required: true
    description: "Standard HNS Storage Account" 
  STANDARD_HNS_KEY: 
    required: true
    description: "Standard HNS Storage Account Key"
  PREMIUM_HNS_ACCOUNT:
    required: true
    description: "Premium HNS Storage Account"  
  PREMIUM_HNS_KEY:
    required: true
    description: "Premium HNS Storage Account Key"  
  BENCH_CONTAINER:
    required: true
    description: "Container for benchmarking" 
  GITHUB_TOKEN:
    required: true
    description: "GitHub Token"
  CACHE_MODE:
    required: true
    description: "Cache mode for testing"

runs:
  using: "composite"

  steps:
    # Print the host info
    - name: 'Host info'
      shell: bash
      run: hostnamectl
        
    # Install Fuse3
    - name: "Install Fuse3"
      shell: bash
      run: |
        sleep 30
        sudo systemctl stop apt-daily.timer || true
        echo "Add Lock Timeout for apt package manager"
        sudo sh -c 'echo "DPkg::Lock::Timeout \"120\";" > /etc/apt/apt.conf.d/99timeout'
        sudo ps -aux | grep -iE "apt"
        sudo killall apt apt-get || true
        yes | sudo fuser -vik -TERM /var/lib/dpkg/lock /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock || true
        echo "Released any lock if some other process has acquired"
        sudo dpkg --configure -a
        echo "Starting Updates and Installation of Packages"
        sudo apt-get update --fix-missing
        sudo apt-get install -y fuse3 libfuse3-dev gcc mdadm

    # Install Tools
    - name: "Install Tools"
      shell: bash
      run: |
        sudo apt-get install fio jq python3 -y

    # Install GoLang
    - name: "Install Go"
      shell: bash
      run: |
        ./go_installer.sh ../ &> /dev/null
        go version

    # Build Blobfuse2
    - name: "Build Blobfuse2"
      shell: bash
      run: |
        ./build.sh &> /dev/null

    # Run binary and validate the version
    - name: "Validate Version"
      shell: bash
      run: |
        sudo cp ./blobfuse2 /usr/bin/
        which blobfuse2
        blobfuse2 --version

    - name: "Create Env variables for account name and key"
      shell: bash
      run: |
        if [ "${{ matrix.TestType }}" == "standard" ]; then
          echo "Create standard account env"
          echo "AZURE_STORAGE_ACCOUNT=${{ inputs.STANDARD_ACCOUNT }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCESS_KEY=${{ inputs.STANDARD_KEY }}" >> $GITHUB_ENV
        elif [ "${{ matrix.TestType }}" == "premium" ]; then
          echo "Create premium account env"
          echo "AZURE_STORAGE_ACCOUNT=${{ inputs.PREMIUM_ACCOUNT }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCESS_KEY=${{ inputs.PREMIUM_KEY }}" >> $GITHUB_ENV
        elif [ "${{ matrix.TestType }}" == "standard_hns" ]; then
          echo "Create standard hns account env"
          echo "AZURE_STORAGE_ACCOUNT=${{ inputs.STANDARD_HNS_ACCOUNT }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCESS_KEY=${{ inputs.STANDARD_HNS_KEY }}" >> $GITHUB_ENV
        elif [ "${{ matrix.TestType }}" == "premium_hns" ]; then
          echo "Create premium hns account env"
          echo "AZURE_STORAGE_ACCOUNT=${{ inputs.PREMIUM_HNS_ACCOUNT }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCESS_KEY=${{ inputs.PREMIUM_HNS_KEY }}" >> $GITHUB_ENV
        fi

    # Create the block_cache config file for testing
    - name: "Create config file for account type: ${{ matrix.TestType }}"
      if : ${{ inputs.CACHE_MODE == 'block_cache' }}
      shell: bash
      run: |
        blobfuse2 gen-test-config --config-file=azure_block_bench.yaml --container-name=${{ inputs.BENCH_CONTAINER }}  --output-file=./config.yaml
        cat ./config.yaml

    - name: "Create config file for account type: ${{ matrix.TestType }}"
      if : ${{ inputs.CACHE_MODE == 'file_cache' }}
      shell: bash
      run: |
        blobfuse2 gen-test-config --config-file=azure_key_perf.yaml --container-name=${{ inputs.BENCH_CONTAINER }} --temp-path=/mnt/localssd/tempcache --output-file=./config.yaml
        cat ./config.yaml

    - name: "Mount the disk"
      if : ${{ inputs.ARCH == 'ARM64' }}
      shell: bash
      run: |
        df -h
        lsblk -o NAME,MODEL,SIZE,TYPE,MOUNTPOINT
        # Unmount any of the drives if they are currently mounted
        sudo umount /dev/nvme*p1 || true

        # Create the RAID 0 array without interactive prompts
        sudo mdadm --create --verbose /dev/md0 \
        --level=0 \
        --raid-devices=6 \
        --force \
        /dev/nvme0n1p1 /dev/nvme1n1p1 /dev/nvme2n1p1 /dev/nvme3n1p1 /dev/nvme4n1p1 /dev/nvme5n1p1

        sudo mkfs.ext4 -F /dev/md0
        sudo mkdir -p /mnt/localssd
        sudo mount /dev/md0 /mnt/localssd
        sudo chmod 777 /mnt/localssd

        # Verify the new filesystem is mounted
        echo "RAID array created and mounted successfully:"
        df -h

    # Run this test only once for the entire matrix.
    - name: "Run Disk Benchmark tests"
      if : ${{ matrix.TestType == 'premium' && matrix.CacheMode == 'file_cache' }}
      uses: ./.github/actions/disk-benchmark
      with:
        ARCH: ${{ inputs.ARCH }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    # Create the config file for testing
    - name: "Create mount path"
      shell: bash
      run: |
        df -h
        sudo mkdir -p /mnt/blob_mnt
        sudo mkdir -p /mnt/localssd/tempcache
        sudo chmod 777 /mnt/blob_mnt
        sudo chmod 777 /mnt/localssd
        sudo chmod 777 /mnt/localssd/tempcache

    # ---------------------------------------------------------------------------------------------------------------------------------------------------
    # Run the basic tests using FIO

    # Run the Read tests on blobfuse mountpoint
    - name: "Read Test"
      shell: bash
      run: |
        rm -rf /mnt/blob_mnt/*
        rm -rf /mnt/localssd/tempcache/*
        ./perf_testing/scripts/fio_bench.sh /mnt/blob_mnt read ${{ matrix.CacheMode }}

    - name: "Update Bandwidth Results : Read"
      # if: github.event_name != 'workflow_dispatch'
      uses: benchmark-action/github-action-benchmark@v1
      with:
        output-file-path: read/bandwidth_results.json
        tool: 'customBiggerIsBetter'
        max-items-in-chart: 100
        github-token: ${{ inputs.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        gh-pages-branch: benchmarks
        benchmark-data-dir-path: ${{ inputs.ARCH }}/${{ matrix.TestType }}/${{ matrix.CacheMode }}/bandwidth/read

    - name: "Update Latency Results : Read"
      # if: github.event_name != 'workflow_dispatch'
      uses: benchmark-action/github-action-benchmark@v1
      with:
        output-file-path: read/latency_results.json
        tool: 'customSmallerIsBetter'
        max-items-in-chart: 100
        github-token: ${{ inputs.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        gh-pages-branch: benchmarks
        benchmark-data-dir-path: ${{ inputs.ARCH }}/${{ matrix.TestType }}/${{ matrix.CacheMode }}/time/read

    # Run the Write tests on blobfuse mountpoint
    - name: "Write Test"
      shell: bash
      run: |
        rm -rf /mnt/blob_mnt/*
        rm -rf /mnt/localssd/tempcache/*
        ./perf_testing/scripts/fio_bench.sh /mnt/blob_mnt write ${{ matrix.CacheMode }}

    - name: "Update Bandwidth Results : Write"
      # if: github.event_name != 'workflow_dispatch'
      uses: benchmark-action/github-action-benchmark@v1
      with:
        output-file-path: write/bandwidth_results.json
        tool: 'customBiggerIsBetter'
        max-items-in-chart: 100
        github-token: ${{ inputs.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        gh-pages-branch: benchmarks
        benchmark-data-dir-path: ${{ inputs.ARCH }}/${{ matrix.TestType }}/${{ matrix.CacheMode }}/bandwidth/write

    - name: "Update Latency Results : Write"
      # if: github.event_name != 'workflow_dispatch'
      uses: benchmark-action/github-action-benchmark@v1
      with:
        output-file-path: write/latency_results.json
        tool: 'customSmallerIsBetter'
        max-items-in-chart: 100
        github-token: ${{ inputs.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        gh-pages-branch: benchmarks
        benchmark-data-dir-path: ${{ inputs.ARCH }}/${{ matrix.TestType }}/${{ matrix.CacheMode }}/time/write

    # ---------------------------------------------------------------------------------------
