import json
import os
import requests
from openai import OpenAI
from azure.identity import DefaultAzureCredential, get_bearer_token_provider

# -----------------------------
# Load GitHub event payload
# -----------------------------
with open(os.environ["GITHUB_EVENT_PATH"], "r") as f:
    event = json.load(f)

is_issue = "issue" in event
is_discussion = "discussion" in event

if is_issue:
    title = event["issue"]["title"]
    body = event["issue"].get("body", "")
    comments_url = event["issue"]["comments_url"]
elif is_discussion:
    title = event["discussion"]["title"]
    body = event["discussion"].get("body", "")
    comments_url = event["discussion"]["comments_url"]
else:
    dry_run = os.getenv("DRY_RUN", "false").lower() == "true"
    if not dry_run:
        raise RuntimeError("Unsupported GitHub event")
    title = os.getenv("MOCK_TITLE", "Dry-run workflow test")
    body = os.getenv("MOCK_BODY", "No issue/discussion payload found; using dry-run fallback.")
    repository = os.getenv("GITHUB_REPOSITORY", "owner/repo")
    comments_url = f"https://api.github.com/repos/{repository}/issues/1/comments"

# -----------------------------
# Build prompt
# -----------------------------
prompt = f"""
New GitHub item received.

Title:
{title}

Description:
{body}

Please analyze and provide a helpful response.
"""

# -----------------------------
# Call Azure AI Foundry Agent
# -----------------------------
dry_run = os.getenv("DRY_RUN", "false").lower() == "true"
token_provider = get_bearer_token_provider(
    DefaultAzureCredential(),
    "https://ai.azure.com/.default"
)

client = OpenAI(
    api_key=token_provider,
    base_url=os.environ["FOUNDRY_BASE_URL"],
    default_query={"api-version": os.environ["FOUNDRY_API_VERSION"]}
)

response = client.responses.create(
    input=prompt,
    timeout=60
)

agent_reply = response.output_text.strip()

# -----------------------------
# Prepend AI disclaimer
# -----------------------------
final_reply = f"""⚠️ **AI‑generated response**

This response was generated by an AI agent and may not be fully accurate.  
Please validate recommendations before acting on them.

---

{agent_reply}
"""

if dry_run:
    question = f"Title: {title}\nDescription: {body}"
    print("DRY_RUN enabled. Skipping GitHub comment post.")
    print(f"Target URL: {comments_url}")
    print("----- Validation Q&A -----")
    print("Question Asked:")
    print(question)
    print()
    print("Agent Answer:")
    print(final_reply)
    print("----- End Validation Q&A -----")
    raise SystemExit(0)

# -----------------------------
# Post reply back to GitHub
# -----------------------------
headers = {
    "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
    "Accept": "application/vnd.github+json",
}

post_resp = requests.post(
    comments_url,
    headers=headers,
    json={"body": final_reply},
)

post_resp.raise_for_status()