name: BlobFuse CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install basic packages
      run: sudo apt-get install pkg-config cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ -y
    - name: Install libfuse
      run: sudo apt-get install libfuse-dev -y
    - name: Install golang
      run: sudo apt install golang-go
    - name: Prepare for build
      run: chmod +x build.sh
    - name: Bulid blobFuse
      run: ./build.sh
    - name: Test Version
      run: ./build/blobfuse --version
    - name: Create Mount Directory
      run: mkdir blob_mnt
    - name: Create Cache Directory
      run: mkdir /mnt/blobfusetmp
    - name: Mount container
      env:
        MOUNT_DIR: `pwd`/blob_mnt
        TEMP_DIR: /mnt/blobfusetmp
        CONT_NAME: ${{STO_CONT_NAME}}
        AZURE_STORAGE_ACCOUNT: ${{ secrets.STO_ACC_TEST1 }}
        AZURE_STORAGE_ACCESS_KEY: ${{ secrets.STO_KEY_TEST1 }}
      run: ./build/blobfuse $MOUNT_DIR --tmp-path=$TEMP_DIR --container-name=${{ secrets.STO_CONT_NAME }} -o allow_other --log-level=LOG_DEBUG
    - name: Check directory listing
      env:
        MOUNT_DIR: `pwd`/blob_mnt
      run: ls -l $MOUNT_DIR
    -name: Unmount container
     env:
        MOUNT_DIR: `pwd`/blob_mnt
     run:  fusermount -u $MOUNT_DIR
    
        
    
