name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ -y
	  run: sudo apt install golang-go
    - name: make
	  run: chmod +x build.sh
      run: ./build.sh
    - name: make check
      run: ./build/blobfuse --version
    - name: make distcheck
      run: ./build/blobfuse --version 
