name: Performance Testing
on:
  push:
    branches:
      - main
      - vibhansa/perftestrunner

permissions:
  issues: write
  pull-requests: write

jobs:
  PerfTesting:
    runs-on: [self-hosted, 1ES.Pool=blobfuse2-github-pool]
    timeout-minutes: 360

    steps:
      # Print the host info
      - name: 'Host info'
        run: hostnamectl
          
      # Install Fuse3
      - name: "Install Fuse3"
        run: |
          sudo apt-get clean
          sudo apt-get update --fix-missing
          sudo apt-get install fuse3 libfuse3-dev gcc -y

        # Checkout main branch
      - name: 'Checkout Main'
        uses: actions/checkout@v4.1.1

      # Install GoLang
      - name: "Install Go"
        run: |
          ./go_installer.sh ../
          go version
        working-directory: ${{ github.workspace }}

      # Build Blobfuse2
      - name: "Build Blobfuse2"
        run: |
          ./build.sh
        working-directory: ${{ github.workspace }}

      # Run binary and validate the version
      - name: "Validate Version"
        run: |
          ./blobfuse2 --version
        working-directory: ${{ github.workspace }}

      - name: "Update Benchmark Results"
        uses: benchmark-action/github-action-benchmark@v1
        with:
          output-file-path: benchmark/results.json
          tool: 'customBiggerIsBetter'
          alert-threshold: "200%"
          max-items-in-chart: 50
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          auto-push: true
          comment-on-alert: true
          gh-pages-branch: "benchmarks"
          benchmark-data-dir-path: bandwidth
          
  
        
