name: Performance Testing
on:
  push:
    branches:
      - main
      - vibhansa/perftestrunner

permissions:
  issues: write
  pull-requests: write

jobs:
  PerfTesting:
    runs-on: [self-hosted, 1ES.Pool=blobfuse2-github-pool]
    timeout-minutes: 360

    steps:
      - name: 'Host info'
        run: hostnamectl
          
      - name: "Install Dependencies"
        run: |
          sudo apt-get install fuse3 libfuse3-dev -y

      - name: 'Checkout Main'
        uses: actions/checkout@v4.1.1

      - name: "Install Go"
        run: |
          ./go_installer.sh ../
          go version
        working-directory: ${{ github.workspace }}

      - name: "Build Blobfuse2"
        run: |
          ./build.sh
        working-directory: ${{ github.workspace }}


      - name: "Validate Version"
        run: |
          ./blobfuse2 --version
        working-directory: ${{ github.workspace }}

        
