# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  workflow_dispatch: 
    inputs:
      run:
        description: 'Run the workflow'
        required: true
        default: true
        type: boolean 
  push:
    branches: [ "main", master, "blobfuse/2*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", master, "blobfuse/2*" ]
  schedule:
    - cron: '31 19 * * 1'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    name: Build
    runs-on: "ubuntu-22.04"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Blobfuse2
        run: | 
          sudo apt-get install fuse3 libfuse3-dev -y
          go build -o blobfuse2
          ls -l

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: './blobfuse2'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results-binary.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: List Issues
        run: |
          cat trivy-results-binary.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-binary.sarif'
